export const ORDER_ADMIN_LIST_REQUEST = "ORDER_ADMIN_LIST_REQUEST";
export const ORDER_ADMIN_LIST_SUCCESS = "ORDER_ADMIN_LIST_SUCCESS";
export const ORDER_ADMIN_LIST_FAIL = "ORDER_ADMIN_LIST_FAIL";
export const ORDER_ADMIN_LIST_RESET = "ORDER_ADMIN_LIST_RESET";

export const ORDER_ADMIN_CREATE_REQUEST = "ORDER_ADMIN_CREATE_REQUEST";
export const ORDER_ADMIN_CREATE_SUCCESS = "ORDER_ADMIN_CREATE_SUCCESS";
export const ORDER_ADMIN_CREATE_FAIL = "ORDER_ADMIN_CREATE_FAIL";
export const ORDER_ADMIN_CREATE_RESET = "ORDER_ADMIN_CREATE_RESET";

export const ORDER_ADMIN_UPDATE_REQUEST = "ORDER_ADMIN_UPDATE_REQUEST";
export const ORDER_ADMIN_UPDATE_SUCCESS = "ORDER_ADMIN_UPDATE_SUCCESS";
export const ORDER_ADMIN_UPDATE_FAIL = "ORDER_ADMIN_UPDATE_FAIL";
export const ORDER_ADMIN_UPDATE_RESET = "ORDER_ADMIN_UPDATE_RESET";

export const ORDER_ADMIN_DETAILS_REQUEST = "ORDER_ADMIN_DETAILS_REQUEST";
export const ORDER_ADMIN_DETAILS_SUCCESS = "ORDER_ADMIN_DETAILS_SUCCESS";
export const ORDER_ADMIN_DETAILS_FAIL = "ORDER_ADMIN_DETAILS_FAIL";
export const ORDER_ADMIN_DETAILS_RESET = "ORDER_ADMIN_DETAILS_RESET";

export const ORDER_ADMIN_DELETE_REQUEST = "ORDER_ADMIN_DELETE_REQUEST";
export const ORDER_ADMIN_DELETE_SUCCESS = "ORDER_ADMIN_DELETE_SUCCESS";
export const ORDER_ADMIN_DELETE_FAIL = "ORDER_ADMIN_DELETE_FAIL";
export const ORDER_ADMIN_DELETE_RESET = "ORDER_ADMIN_DELETE_RESET";
